name       : amtk
version    : 5.2.0
release    : 5
source     :
    - https://download.gnome.org/sources/amtk/5.2/amtk-5.2.0.tar.xz : 820545bb4cf87ecebc2c3638d6b6e58b8dbd60a419a9b43cf020124e5dad7078
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Actions, Menus and Toolbars Kit for GTK+ applications
description: |
    Actions, Menus and Toolbars Kit for GTK+ applications
builddeps  :
    - pkgconfig(gtk+-3.0)
    - gtk-doc
setup      : |
    %configure --disable-static --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
