name       : amtk
version    : 5.6.0
release    : 8
source     :
    - https://download.gnome.org/sources/amtk/5.6/amtk-5.6.0.tar.xz : f3db8797442a9b85062acd0b3e17ac9125a0b487e14216d09b03b08841820eb9
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Actions, Menus and Toolbars Kit for GTK+ applications
description: |
    Actions, Menus and Toolbars Kit for GTK+ applications
builddeps  :
    - pkgconfig(gtk+-3.0)
    - gtk-doc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
