name       : amtk
version    : 5.3.1
release    : 7
source     :
    - https://download.gnome.org/sources/amtk/5.3/amtk-5.3.1.tar.xz : d5aa236c5d71dc41aa4674f345560a67a27f21c0efc97c9b3da09cb582b4638b
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Actions, Menus and Toolbars Kit for GTK+ applications
description: |
    Actions, Menus and Toolbars Kit for GTK+ applications
builddeps  :
    - pkgconfig(gtk+-3.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
