name       : amtk
version    : 5.6.1
release    : 9
source     :
    - https://download.gnome.org/sources/amtk/5.6/amtk-5.6.1.tar.xz : d50115b85c872aac296934b5ee726a3fa156c6f5ad96d27e0edd0aa5ad173228
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Actions, Menus and Toolbars Kit for GTK+ applications
description: |
    Actions, Menus and Toolbars Kit for GTK+ applications
builddeps  :
    - pkgconfig(gtk+-3.0)
    - gtk-doc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
